print("DAILY TEMPERATURE RECEIVED")
d1 = int(input("Enter temperature of day 1: "))
d2 = int(input("Enter temperature of day 2: "))
d3 = int(input("Enter temperature of day 3: "))
d4 = int(input("Enter temperature of day 4: "))
d5 = int(input("Enter temperature of day 5: "))
d6 = int(input("Enter temperature of day 6: "))
d7 = int(input("Enter temperature of day 7: "))
print("DAY 1 TEMP: ", d1)
print("DAY 2 TEMP: ", d2)
print("DAY 3 TEMP: ", d3)
print("DAY 4 TEMP: ", d4)
print("DAY 5 TEMP: ", d5)
print("day 6 TEMP: ", d6)
print("DAY 7 TEMP: ", d7)